### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by Chiaraplizz** [jonmun/EPIC-KITCHENS-100_UDA_TA3N#1]
Hi, 

I noticed the checkpoints.pth files only contain the weights of the prediction layers, and not of the backbone. Did I understand correctly? Are they supposed to be used with the provided features? 

Thanks, 

Chiara

**Comment by jonmun** [comment]
Hi Chiara,

The code uses the provided features. These features are extracted from a TBN model trained on the source domain.

The backbone model isn't needed to replicate the results. I will upload the weights of the backbone after the holidays as I currently don't have access to them.

Best,
Jonathan

**Comment by Chiaraplizz** [comment]
Ok, thanks. I will wait for the weights to be uploaded.

Chiara

**Comment by jonmun** [comment]
Hi Chiara,

The weights of the base model for feature extraction can be found here: https://www.dropbox.com/s/2ct6d750kzfn9qr/TBN_DA.pth.tar?dl=0

The code for backbone model is found here: https://github.com/ekazakos/temporal-binding-network

This should be enough to relplicate the extracted features, therefore closing the issue.
